name: Deploy GitHub Pages

on:
  push:
    branches:
      - main # This will trigger the workflow on pushes to the 'main' branch
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4



      # This step uploads your static files as an artifact for the deploy job
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:

          path: ./

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # Ensures this job runs only after the 'build' job succeeds
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
