name: Deploy to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main  # Or master, or whatever your default branch is

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    # !!! IMPORTANT: Replace 'emailjs-config.js' below
    # if your GitHub Environment has a different name.
    # Based on your screenshot, 'emailjs-config.js' is the likely environment name.
    environment:
      name: emailjs-config.js # Or the exact name of your GitHub Environment
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate emailjs-config.js
        run: |
          echo "Generating emailjs-config.js..."
          # Create the emailjs-config.js file using the secrets
          # The secrets are accessed via the ${{ secrets.SECRET_NAME }} syntax
          echo "const EMAILJS_PUBLIC_KEY = '${{ secrets.EMAILJS_PUBLIC_KEY }}';" > emailjs-config.js
          echo "const EMAILJS_SERVICE_ID = '${{ secrets.EMAILJS_SERVICE_ID }}';" >> emailjs-config.js
          echo "const EMAILJS_TEMPLATE_ID = '${{ secrets.EMAILJS_TEMPLATE_ID }}';" >> emailjs-config.js
          
          echo "emailjs-config.js generated successfully. Contents:"
          cat emailjs-config.js
        # This assumes your secrets in the GitHub Environment are named:
        # EMAILJS_PUBLIC_KEY, EMAILJS_SERVICE_ID, and EMAILJS_TEMPLATE_ID.
        # Adjust these if your secret names are different.

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload everything in the root directory (which includes your index.html,
          # script.js, style.css, and the generated emailjs-config.js)
          path: '.' 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
